### ISSUE TITLE
Language pack inheritance order

### ISSUE THREAD

**Issue by koenner01** [EaDesgin/magento2-romanian-language-pack#4]
Is there a reason why there is no Magento vendor inheritance defined in the language.xml ?
Because currently if we are adding the eadesigndev/ro_ro pack as a parent to our projects pack, the order in packs is:

eadesigndev |ro_RO
Magento|ro_RO
Project|ro_RO

Aren't the translations in this pack supposed to replace the Magento ones ? (because now Magento will replace your packs translations)

**Comment by eadesignro** [comment]
Can you give us  example for the inheritance?

**Comment by koenner01** [comment]
@eadesignro If you add a language pack to your project with inheritance to this pack like

```
<?xml version="1.0"?>
<language xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:App/Language/package.xsd">
    <code>ro_RO</code>
    <vendor>projectname</vendor>
    <package>ro_ro</package>
    <use vendor="eadesigndev" package="ro_ro"/>
</language>
```

The order in which the translations on the frontend will be done will be 

eadesigndev |ro_RO
Magento|ro_RO
Project|ro_RO

So if Magento has a translation for the same line as this pack, the Magento translation will be used!
I assume this pack is supposed to be an improvement to the Magento translations ?
