### ISSUE TITLE
Elementele astea cu % nu trebuie traduse

### ISSUE THREAD

**Issue by mindsoul** [EaDesgin/magento2-romanian-language-pack#6]
%nume,

Comanda dumneavoastră #%id_creștere a fost actualizată la statusul de %status_comandă.

Puteți verifica statusul comenzii dumneavoastră prin conectare la contul dumneavoastră.

Dacă aveți întrebări referitoare la comanda dumneavoastră, ne puteți trimite email la %email_magazin sau sunați-ne la %telefon_magazin.

some comment
Vă mulțumim, %nume_magazin!

**Comment by webraptor** [comment]
Au rezolvat si eu cu un commit ulterior problema. Am facut acum un PR cu ce mai era incorect la variabile traduse. https://github.com/EaDesgin/magento2-romanian-language-pack/pull/7
